export const PARTNER_ACTIONS = {
    FETCH_PARTNERS: 'FETCH_PARTNERS',
    SET_PARTNERS: 'SET_PARTNERS',
    GET_PARTNER: 'GET_PARTNER',
    SET_PARTNER: 'SET_PARTNER',
    ADD_PARTNER: 'ADD_PARTNER',
    EDIT_PARTNER: 'EDIT_PARTNER',
    HIDE_PARTNER: 'HIDE_PARTNER',
    DELETE_PARTNER: 'DELETE_PARTNER',
  };