export const PERSON_ACTIONS = {
    FETCH_PERSONS: 'FETCH_PERSONS',
    SET_PERSONS: 'SET_PERSONS',
    ADD_PERSON: 'ADD_PERSON',
    EDIT_PERSON: 'EDIT_PERSON',
    HIDE_PERSON: 'HIDE_PERSON',
    DELETE_PERSON: 'DELETE_PERSON',
  };