export const POST_ACTIONS = {
    FETCH_POSTS: 'FETCH_POSTS',
    GET_POSTS: 'GET_POSTS',
    FETCH_PARTNER_POSTS: 'FETCH_PARTNER_POSTS',
    GET_PARTNER_POSTS: 'GET_PARTNER_POSTS',
    ADD_POST: 'ADD_POST',
    EDIT_POST: 'EDIT_POST',
    HIDE_POST: 'HIDE_POST',
    DELETE_POST: 'DELETE_POST',
};