export const POST_ACTIONS = {
    FETCH_POSTS: 'FETCH_POSTS',
    SET_POSTS: 'SET_POSTS',
    SET_ALL_POSTS: 'SET_ALL_POSTS',
    FETCH_PARTNER_POSTS: 'FETCH_PARTNER_POSTS',
    GET_PARTNER_POSTS: 'GET_PARTNER_POSTS',
    FETCH_POSTS_FILTERED: 'FETCH_POSTS_FILTERED',
    GET_POSTS_FILTERED: 'GET_POSTS_FILTERED',
    ADD_POST: 'ADD_POST',
    EDIT_POST: 'EDIT_POST',
    HIDE_POST: 'HIDE_POST',
    DELETE_POST: 'DELETE_POST',
    FETCH_ALL_POSTS: 'FETCH_ALL_POSTS'
};